name: jwlife
description: >
  JW Life est une application Flutter visant à moderniser et améliorer JW Library
  en corrigeant ses bugs et en ajoutant des fonctionnalités utiles aux Témoins de
  Jéhovah.
version: 1.4.9
publish_to: "none"

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Core ---
  intl: ^0.20.2
  collection: ^1.19.1
  uuid: ^4.5.2

  # --- System / Device ---
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  app_settings: ^7.0.0
  string_similarity: ^2.1.1
  flutter_local_notifications: ^20.0.0

  # --- Storage & DB ---
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  realm: ^20.2.0

  # --- File & Crypto ---
  file_picker: ^10.3.10
  open_file: ^3.5.11
  archive: ^4.0.7
  encrypt: ^5.0.3
  crypto: ^3.0.7
  mime: ^2.0.0

  # --- Media ---
  video_player: ^2.10.1
  audio_info: ^0.0.3
  flutter_video_info: ^1.3.3
  audio_session: ^0.2.2
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  just_audio_platform_interface: ^4.6.0

  # --- Web & Network ---
  dio: ^5.9.1
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  html: ^0.15.6

  # --- UI / Widgets ---
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  printing: ^5.14.2
  share_plus: ^12.0.1
  table_calendar: ^3.2.0
  flutter_contacts: ^1.1.9+2
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.2.3
  reorderables: ^0.6.0
  dotted_border: ^3.1.0
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  gal: ^2.3.2
  pip_view: 0.9.7

  # --- Markdown ---
  gpt_markdown: ^1.1.5

  # --- State management ---
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/html/
    - assets/meps/
    - assets/icons/
    - assets/icons/bookmarks/dark/
    - assets/icons/bookmarks/light/
    - assets/images/
    - assets/userData/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: jw-icons
      fonts:
        - asset: assets/fonts/jw-icons.ttf
